version: '0.2'
language: en,en-GB
useGitignore: true
ignorePaths:
  - bun.lock
  - coverage/**
  - dist/**
  - node_modules/**
  - playwright-report/**
  - test-results/**
words:
  - Bun
  - Creepiest
  - Knip
  - Lefthook
  - Oxfmt
  - Oxlint
  - Turborepo
  - bunx
  - commitlint
  - cspell
  - czg
  - deadcode
  - depcruise
  - npmjs
  - oxc
  - pcss
  - tsgolint
  - worktree
